-------------------fileName------------------
libsecmain.x86.so
libsecpreload.so
libsecmain.so
libsecexe.x86.so
libsecpreload.x86.so
bangcle_classes.jar
libsecexe.so
-------------------string------------------
assets/libsecpreload.so
libsecpreload.so
assets/libsecpreload.x86.so
libsecpreload.x86.so
assets/libsecexe.x86.so
libsecmain.x86.so
-------------------pkgName------------------
Lcom/bangcle/everisk/stub
Lcom/secneo/guard
-------------------clsName------------------
ACall
-------------------methodName------------------
-------------------fieldName------------------
-------------------clsSig------------------
Lcom/bangcle/everisk/stub/AlarmReceiver;
Lcom/secneo/guard/Util;
Lcom/secneo/guard/MyClassLoader;
Lcom/secneo/guard/ACall;
-------------------exFieldName------------------
-------------------exMethodName------------------
-------------------exClsName------------------
-------------------exPkgName------------------
-------------------exClsSig------------------
