-------------------fileName------------------
legudzbait
unity.config
libshella-2.6.0.so
tencent_stub
libBugly.so
libshellx-2.6.0.so
libufix.so
-------------------string------------------
TxAppEntry
com.tencent.bugly.unity.UnityAgent
[1] 输出详细的Bugly SDK的Log -- More detailed log of Bugly SDK will be output to logcat;
BUGLY_APP_VERSION
user_bugly_appid
-------------------pkgName------------------
Lcom/tencent/StubShell
Lcom/tencent/bugly/lejiagu/crashreport/common/info
Lcom/tencent/bugly/lejiagu/crashreport/crash
Lcom/tencent/bugly/lejiagu/crashreport/crash/h5
Lcom/tencent/bugly/lejiagu/crashreport/biz
Lcom/tencent/bugly/lejiagu/crashreport/common/strategy
Lcom/tencent/bugly/lejiagu
Lcom/tencent/bugly/lejiagu/crashreport
Lcom/tencent/bugly/lejiagu/crashreport/inner
Lcom/tencent/bugly/lejiagu/crashreport/crash/jni
Lcom/tencent/bugly/lejiagu/crashreport/crash/anr
Lcom/tencent/bugly/lejiagu/proguard
-------------------clsName------------------
BuglyStrategy$a
TxAppEntry
LeguApplication
BuglyHintException
BuglyLog
BuglyBroadcastRecevier$1
Bugly
-------------------methodName------------------
getBuglyVersion
enableBugly
setLibBuglySOFilePath
setBuglyLogUpload
enableUserBugly
-------------------fieldName------------------
leguFixCount
-------------------clsSig------------------
Lcom/tencent/bugly/lejiagu/proguard/ao;
Lcom/tencent/bugly/lejiagu/crashreport/crash/CrashDetailBean$1;
Lcom/tencent/StubShell/f;
Lcom/tencent/bugly/lejiagu/proguard/v;
Lcom/tencent/bugly/lejiagu/crashreport/crash/h5/c;
Lcom/tencent/bugly/lejiagu/crashreport/crash/anr/TraceFileHelper$1;
Lcom/tencent/bugly/lejiagu/crashreport/common/strategy/StrategyBean$1;
Lcom/tencent/bugly/lejiagu/CrashModule;
Lcom/tencent/bugly/lejiagu/crashreport/crash/anr/a;
Lcom/tencent/bugly/lejiagu/proguard/ag;
Lcom/tencent/bugly/lejiagu/proguard/ap;
Lcom/tencent/bugly/lejiagu/proguard/g;
Lcom/tencent/bugly/lejiagu/proguard/o;
Lcom/tencent/bugly/lejiagu/crashreport/biz/a$a;
Lcom/tencent/bugly/lejiagu/crashreport/common/strategy/StrategyBean;
Lcom/tencent/bugly/lejiagu/BuglyStrategy;
Lcom/tencent/bugly/lejiagu/proguard/n;
Lcom/tencent/bugly/lejiagu/crashreport/crash/anr/TraceFileHelper;
Lcom/tencent/bugly/lejiagu/crashreport/crash/jni/b;
Lcom/tencent/bugly/lejiagu/proguard/y;
Lcom/tencent/bugly/lejiagu/proguard/r$a;
Lcom/tencent/bugly/lejiagu/proguard/ak;
Lcom/tencent/bugly/lejiagu/proguard/ah;
Lcom/tencent/bugly/lejiagu/crashreport/inner/InnerAPI;
Lcom/tencent/bugly/lejiagu/crashreport/crash/anr/TraceFileHelper$2;
Lcom/tencent/bugly/lejiagu/proguard/f;
Lcom/tencent/bugly/lejiagu/proguard/q;
Lcom/tencent/bugly/lejiagu/crashreport/crash/h5/a;
Lcom/tencent/bugly/lejiagu/crashreport/biz/b$1;
Lcom/tencent/bugly/lejiagu/proguard/aa;
Lcom/tencent/StubShell/TxAppEntry;
Lcom/tencent/bugly/lejiagu/crashreport/crash/jni/NativeExceptionHandler;
Lcom/tencent/bugly/lejiagu/crashreport/crash/d$2;
Lcom/tencent/StubShell/SystemClassLoaderInjector;
Lcom/tencent/bugly/lejiagu/crashreport/crash/anr/b;
Lcom/tencent/bugly/lejiagu/proguard/v$a;
Lcom/tencent/bugly/lejiagu/proguard/x;
Lcom/tencent/StubShell/d;
Lcom/tencent/bugly/lejiagu/proguard/a;
Lcom/tencent/bugly/lejiagu/proguard/i;
Lcom/tencent/bugly/lejiagu/crashreport/crash/a;
Lcom/tencent/StubShell/LeguApplication;
Lcom/tencent/bugly/lejiagu/crashreport/BuglyLog;
Lcom/tencent/bugly/lejiagu/crashreport/crash/d;
Lcom/mixClass;
Lcom/tencent/bugly/lejiagu/crashreport/common/strategy/a;
Lcom/tencent/bugly/lejiagu/crashreport/crash/d$3;
Lcom/tencent/bugly/lejiagu/crashreport/crash/c$1;
Lcom/tencent/StubShell/c;
Lcom/tencent/bugly/lejiagu/crashreport/crash/anr/b$1;
Lcom/tencent/bugly/lejiagu/proguard/aj;
Lcom/tencent/bugly/lejiagu/proguard/h;
Lcom/tencent/bugly/lejiagu/Bugly;
Lcom/tencent/bugly/lejiagu/proguard/s;
Lcom/tencent/bugly/lejiagu/crashreport/crash/jni/NativeCrashHandler;
Lcom/tencent/bugly/lejiagu/proguard/ac;
Lcom/tencent/bugly/lejiagu/proguard/c;
Lcom/tencent/bugly/lejiagu/a;
Lcom/tencent/bugly/lejiagu/crashreport/common/info/AppInfo;
Lcom/tencent/bugly/lejiagu/crashreport/biz/a$b;
Lcom/tencent/bugly/lejiagu/proguard/m$a;
Lcom/tencent/bugly/lejiagu/crashreport/crash/BuglyBroadcastRecevier$1;
Lcom/tencent/bugly/lejiagu/crashreport/crash/jni/NativeCrashHandler$1;
Lcom/tencent/bugly/lejiagu/crashreport/biz/UserInfoBean$1;
Lcom/tencent/StubShell/b;
Lcom/tencent/bugly/lejiagu/proguard/k;
Lcom/tencent/bugly/lejiagu/proguard/r;
Lcom/tencent/bugly/lejiagu/crashreport/crash/e;
Lcom/tencent/bugly/lejiagu/crashreport/common/info/PlugInBean;
Lcom/tencent/bugly/lejiagu/crashreport/crash/anr/TraceFileHelper$a;
Lcom/tencent/bugly/lejiagu/crashreport/crash/jni/a;
Lcom/tencent/bugly/lejiagu/proguard/ad;
Lcom/tencent/bugly/lejiagu/proguard/b;
Lcom/tencent/bugly/lejiagu/crashreport/biz/UserInfoBean;
Lcom/tencent/StubShell/FileUtils;
Lcom/tencent/bugly/lejiagu/crashreport/crash/anr/b$2;
Lcom/tencent/bugly/lejiagu/proguard/v$1;
Lcom/tencent/bugly/lejiagu/crashreport/crash/d$1;
Lcom/tencent/bugly/lejiagu/proguard/z;
Lcom/tencent/bugly/lejiagu/proguard/al;
Lcom/tencent/bugly/lejiagu/proguard/j;
Lcom/tencent/StubShell/a;
Lcom/tencent/bugly/lejiagu/proguard/u;
Lcom/tencent/bugly/lejiagu/crashreport/biz/a;
Lcom/tencent/bugly/lejiagu/crashreport/common/info/a;
Lcom/tencent/bugly/lejiagu/proguard/e;
Lcom/tencent/bugly/lejiagu/proguard/ae;
Lcom/tencent/bugly/lejiagu/crashreport/BuglyHintException;
Lcom/tencent/bugly/lejiagu/crashreport/crash/anr/TraceFileHelper$b;
Lcom/tencent/bugly/lejiagu/b;
Lcom/tencent/bugly/lejiagu/proguard/t;
Lcom/tencent/bugly/lejiagu/crashreport/common/info/PlugInBean$1;
Lcom/tencent/bugly/lejiagu/crashreport/biz/a$1;
Lcom/tencent/bugly/lejiagu/proguard/m;
Lcom/tencent/bugly/lejiagu/proguard/am;
Lcom/tencent/bugly/lejiagu/crashreport/crash/BuglyBroadcastRecevier;
Lcom/tencent/bugly/lejiagu/crashreport/crash/c;
Lcom/tencent/bugly/lejiagu/crashreport/CrashReport$CrashHandleCallback;
Lcom/tencent/StubShell/e;
Lcom/tencent/bugly/lejiagu/crashreport/crash/c$2;
Lcom/tencent/bugly/lejiagu/proguard/d;
Lcom/tencent/bugly/lejiagu/crashreport/biz/b$2;
Lcom/tencent/bugly/lejiagu/crashreport/crash/b$1;
Lcom/tencent/bugly/lejiagu/crashreport/crash/h5/b;
Lcom/tencent/bugly/lejiagu/proguard/p;
Lcom/tencent/bugly/lejiagu/crashreport/biz/b;
Lcom/tencent/bugly/lejiagu/BuglyStrategy$a;
Lcom/tencent/bugly/lejiagu/crashreport/crash/CrashDetailBean;
Lcom/tencent/StubShell/g;
Lcom/tencent/bugly/lejiagu/proguard/t$1;
Lcom/tencent/bugly/lejiagu/proguard/an;
Lcom/tencent/bugly/lejiagu/crashreport/crash/h5/H5JavaScriptInterface;
Lcom/tencent/bugly/lejiagu/proguard/l;
Lcom/tencent/bugly/lejiagu/proguard/w;
Lcom/tencent/bugly/lejiagu/proguard/h$a;
Lcom/tencent/bugly/lejiagu/proguard/ai;
Lcom/tencent/bugly/lejiagu/proguard/af;
Lcom/tencent/bugly/lejiagu/crashreport/crash/b;
Lcom/tencent/bugly/lejiagu/crashreport/crash/d$4;
Lcom/tencent/bugly/lejiagu/crashreport/common/strategy/a$1;
Lcom/tencent/StubShell/SystemInfoException;
Lcom/tencent/StubShell/ZipUtil;
Lcom/tencent/bugly/lejiagu/crashreport/CrashReport;
Lcom/tencent/bugly/lejiagu/crashreport/CrashReport$UserStrategy;
Lcom/tencent/bugly/lejiagu/proguard/ab;
-------------------exFieldName------------------
-------------------exMethodName------------------
-------------------exClsName------------------
-------------------exPkgName------------------
-------------------exClsSig------------------
