-------------------fileName------------------
-------------------string------------------
ACTION_ACCESSIBILITY_FOCUS
mPopup
http://
ACTION_FOCUS
getScript
ACTION_SCROLL_BACKWARD
true
ACTION_CLEAR_FOCUS
scaleX
setExclusiveCheckable
https
ACTION_SELECT
mOverlapAnchor
US-ASCII
setChildrenDrawingOrderEnabled
ACTION_PREVIOUS_HTML_ELEMENT
doBeforeTextChanged
mMinWidth
link
rotation
scrolling
makeOptionalFitsSystemWindows
ACTION_NEXT_HTML_ELEMENT
activity
ACTION_NEXT_AT_MOVEMENT_GRANULARITY
Content-Type
addLikelySubtags
onLoaderReset
weight
ACTION_COPY
mAnchor
mIsChildViewEnabled
computeFitSystemWindows
category
doAfterTextChanged
GET
ACTION_LONG_CLICK
clipboard
ACTION_CLEAR_SELECTION
ACTION_SET_SELECTION
ACTION_SCROLL_FORWARD
ACTION_CLEAR_ACCESSIBILITY_FOCUS
ensureImeVisible
http
android.intent.action.VIEW
connectivity
mListener
ACTION_CLICK
%
POST
text/plain
onLoadFinished
ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY
ACTION_PASTE
ACTION_CUT
showSoftInputUnchecked
-------------------pkgName------------------
-------------------clsName------------------
SearchView
-------------------methodName------------------
onAnimationStart
getTransformation
getIntent
registerReceiver
getMeasuredWidthAndState
isCheckable
startNestedScroll
setMaxWidth
setImeOptions
collapseActionView
getPaddingTop
setInputType
setClickable
getQuery
setOnQueryTextListener
hasNestedScrollingParent
setOnCloseListener
getPaddingRight
setSubmitButtonEnabled
unregisterObserver
setTransformationMethod
getWindowVisibility
registerObserver
performAction
dispatchNestedScroll
notifyChanged
dump
setEmptyView
setSearchableInfo
setActionProvider
setQueryHint
getTextSize
setOnItemClickListener
setTextSize
getTextColors
onScroll
startActivityForResult
onAnimationEnd
unregisterReceiver
getSelectedItemId
onNestedPreFling
setIconified
findAccessibilityNodeInfosByText
getNestedScrollAxes
onReceive
setQuery
onKeyUp
invalidateDrawable
setOnActionExpandListener
getRotation
getApplicationContext
getSubtitle
setLongClickable
requestFocus
onDraw
getSelectedItemPosition
onKeyDown
onStopNestedScroll
dispatchNestedPreFling
onPostExecute
onNestedScrollAccepted
b
setSubtitle
values
findFocus
setCancelable
putAll
dispatchNestedPreScroll
setOnLongClickListener
setOnCancelListener
setQueryRefinementEnabled
onCreateDrawableState
onNestedPreScroll
isChecked
a_
finish
dispatchNestedFling
b_
setSelection
isNestedScrollingEnabled
setNestedScrollingEnabled
createFromParcel
getActionProvider
-------------------fieldName------------------
CREATOR
title
O
icon
-------------------clsSig------------------
-------------------exFieldName------------------
-------------------exMethodName------------------
-------------------exClsName------------------
-------------------exPkgName------------------
-------------------exClsSig------------------
